### ISSUE TITLE
[ Feat ] Customizable error messages

### ISSUE THREAD

**Issue by w00fz** [dev-xo/remix-auth-otp#8]
Currently all the thrown errors are hardcoded. Would be great being able to customize the wording or the language.

**Comment by dev-xo** [comment]
Happy to see this Issue @w00fz

Before creating a PR, or even start working on it, could we write a simple implementation plan?
Do you have something in mind?

I was thinking about simplifying current Errors, making them shorter and more concise.
This also could be useful whenever we are targeting for them.

The implementation should be kinda simple.
- Extending the Strategy Instance options with a new `CustomErrors` or similar name Object / Interface.
- Defining the `defaults` for the newly created Interface, in case is not user provided.

And more or less the same as we did with the Magic Link.

The tests for the Errors should also be valid for this new feature.
In case them are not, could be easily fixed.

Will like to know your plan / thoughts!

**Comment by w00fz** [comment]
Hey @dev-xo,

I think extending and exposing the options interface for customizing errors is a good way to give control over them.

I also believe it's a good opportunity for tweaking the default error messages and make them as descriptive and indicative of what the actual error is, so that when one decides to override them, the errors can function as documentation as well.

For example, I know for a fact I wouldn't leave `Code is not active` or `OTP Code not found` as displayed errors, since they are too much of a hint for malicious activity, however having them explicit like that will help identify when the message I'm customizing will actually occur. People who don't really mind those explicit errors, they would just work as fine.

**Comment by dev-xo** [comment]
I'm agree with you @w00fz .

I would like to see a descriptive implementation from your side, and also know if you wanna work on it, otherwise would be a pleasure for me to hope on the code.

You already got my trust, and I know both of us are able to accomplish this feature in the best way possible.
Saying this, gonna summarize a possible implementation we can follow:

- Make base errors as descriptive and indicative as we can, trying to not reveal hits for possible malicious activities.
- Create a `customErrors` Object and it's Interface fort he Strategy Instance.
- The `customError` Object could contain varios properties like `invalidCode | invalidOtp`, `invalidEmail`, and so on.
- Defining the defaults for the `customErrors` Object in case them are not user provided.

And as I said before, more or less the same as we did with the Magic Link implementation.
Also, not sure If you would like to have internal Error codes like `E10 | E100 ..`.
Not sure if that would help us, or make the package harder to maintain. In any case, it's an option im leaving here.

I would like to know your opinion, implementation or your thoughts about this.
Also feel free to fork the project again, or update it. I've added `husky` to it, for some Conventional Commits on the newly PR. That could help me create an easier Release version, with all the changes we've made.

I think you have to run `npm run prepare` for the husky thing.
And this is all. Would love to know if you wanna be in charge of this feature, or allow me to do it.
I'm okay with both options.

Again thank you for the interest and for everything you've did so far! :)

**Comment by w00fz** [comment]
Hey @dev-xo,

Appreciate the trust you put on me but please don't feel obligated to wait on my approval. 

I don't think I will have much time in the near future to take a stab at the custom errors enhancements but I like where you are heading with it. My only advise would be to keep things simple!

**Comment by dev-xo** [comment]
All right @w00fz ! Sounds good to me mate!

Besides the project is mine, I do not wanna take the full control over it, especially if I trust someone, and also that someone does an amazing job every time touches it.

I do not have much time either, but I can look into it in the next few days.
And yes! Add Issues / Suggestions that you think could improve the package. I'm up for it!

Happy to have you on here, and as a reminder, do not feel obligated to do anything for the project, no matter if you are a collaborator. Having you on here opening Issues / suggestions it's enough for me!
